stages:
    - diff: "fast_carpenter.Define"
    - var_def: "fast_carpenter.Define"
    - event_selection: 'fast_carpenter.CutFlow'
    - histogram: "fast_carpenter.BinnedDataframe"

var_def:
    variables:
        - nCaloTower: {reduce: count_nonzero, formula: 'l1CaloTowerTree.L1CaloTowerTree.L1CaloTower.et'}

event_selection:
    selection:
        All:
            - nCaloTower > 0

diff:
    variables:
        - diff_emu: "l1CaloTowerTree.L1CaloTowerTree.L1CaloTower.iet - l1CaloTowerTree.L1CaloTowerTree.L1CaloTower.et"

histogram:
    binning:
        - {in: diff_emu, bins: {edges: [-100, -50, -20, 0, 20, 50, 100]}}
        - {in: "nCaloTower", out: nCaloTower, bins: {edges: [0, 1, 5, 10, 20]}}
        - {in: "l1CaloTowerTree__DOT__L1CaloTowerTree__DOT__L1CaloTower__DOT__iet", out: iet, bins: {edges: [0, 10, 20, 30, 50, 100, 200, 400, 700, 1000]}}
        # TODO: binning in different jaggedness (a way to normalize?)
        # - {in: "l1CaloTowerEmuTree__DOT__L1CaloTowerTree__DOT__L1CaloTower__DOT__iet", out: emu_iet, bins: {edges: [0, 200, 400, 700, 1000]}}
